CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408052126_InitialCreate') THEN
    CREATE TABLE "BudgetItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Category" text NOT NULL,
        "AmountLimit" numeric NOT NULL,
        "Period" text NOT NULL,
        "BudgetMonth" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_BudgetItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408052126_InitialCreate') THEN
    CREATE TABLE "SavingsGoals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "TargetAmount" numeric NOT NULL,
        "CurrentAmount" numeric NOT NULL,
        "Deadline" timestamp with time zone,
        "Notes" text,
        "IsDone" boolean NOT NULL,
        CONSTRAINT "PK_SavingsGoals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408052126_InitialCreate') THEN
    CREATE TABLE "Transactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Amount" numeric NOT NULL,
        "Category" text NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "Description" text,
        "Notes" text,
        "CategoryIcon" text NOT NULL,
        "IsIncome" boolean NOT NULL,
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260408052126_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260408052126_InitialCreate', '10.0.5');
    END IF;
END $EF$;
COMMIT;

